[[CURRENCIES]]
code="GTSTORE"
issuer="GBCX7CGY3DI5XM5XDWD3TVNM4REG73ZYSLDFZSTW7MTRUFKS662HWSYS"
name="GTSTORE Stablecoin"
desc="A gatget store on pi."
image="https://https://gt-store-main.vercel.app//gtstore.png"

